<?php

use App\Authorization\SystemContext;
use App\Enums\HealthSource;
use App\Enums\ProjectHealth;
use App\Enums\StepType;
use App\Enums\UserRole;
use App\Models\Project;
use App\Models\Step;
use App\Models\Tracker;
use App\Services\Projects\ActivityRecorder;
use App\Services\Projects\MovementRecorder;
use App\Services\Projects\ProjectService;
use App\Services\Trackers\TrackerService;
use Illuminate\Support\Facades\DB;

/**
 * The movement history substrate — the table every metric is derived from.
 */
beforeEach(function () {
    $this->admin = makeUser('admin@example.com', UserRole::Admin);
    bindContextFor($this->admin);

    $this->tracker = app(TrackerService::class)->create(['name' => 'IT Technical'], $this->admin);

    $this->steps = SystemContext::run(fn () => Step::where('tracker_id', $this->tracker->id)
        ->orderBy('position')->get()->keyBy('name'));
});

describe('a new tracker is immediately usable', function () {

    it('seeds four default steps satisfying the active/terminal invariant', function () {
        // FR-2.5 — a tracker with no steps has nowhere to put a card, so an unseeded
        // tracker is a dead end that looks like a bug.
        expect($this->steps->keys()->all())->toBe(['Backlog', 'New', 'In Progress', 'Done'])
            ->and($this->steps['In Progress']->type)->toBe(StepType::Active)
            ->and($this->steps['Done']->type)->toBe(StepType::Terminal);
    });

    it('makes the creating admin a member', function () {
        expect($this->admin->isMemberOf($this->tracker))->toBeTrue()
            ->and(DB::table('tracker_members')->where('tracker_id', $this->tracker->id)->count())->toBe(1);
    });
});

describe('project creation opens the first movement', function () {

    it('never leaves a project without an open movement or an activity clock', function () {
        $project = app(ProjectService::class)->create($this->tracker, ['name' => 'Firewall upgrade'], $this->admin);

        $open = DB::table('project_step_movements')
            ->where('project_id', $project->id)->whereNull('exited_at')->first();

        expect($open)->not->toBeNull()
            ->and($open->seq)->toBe(1)
            ->and($open->reason)->toBe('created')
            ->and($open->from_step_id)->toBeNull()
            // metrics-4: a NULL clock makes the stall predicate evaluate to NULL, so the
            // project would be permanently invisible to stall detection.
            ->and($project->last_activity_at)->not->toBeNull();
    });

    it('snapshots the department onto the movement row', function () {
        // metrics-1: department is editable per project, so without a snapshot a rebuild
        // would stamp today's department across all of history.
        $dept = DB::table('departments')->insertGetId([
            'name' => 'Networking', 'created_at' => now(), 'updated_at' => now(),
        ]);

        $project = app(ProjectService::class)->create(
            $this->tracker, ['name' => 'Core switch', 'department_id' => $dept], $this->admin,
        );

        $movement = DB::table('project_step_movements')->where('project_id', $project->id)->first();

        expect((int) $movement->department_id)->toBe($dept);

        // Re-filing the project must NOT rewrite the historical row.
        $project->forceFill(['department_id' => null])->save();

        expect((int) DB::table('project_step_movements')->where('id', $movement->id)->value('department_id'))
            ->toBe($dept);
    });
});

describe('moving a project', function () {

    beforeEach(function () {
        $this->project = app(ProjectService::class)->create($this->tracker, ['name' => 'VPN rollout'], $this->admin);
    });

    it('closes the previous interval and opens exactly one new one', function () {
        app(MovementRecorder::class)->recordMove($this->project, $this->steps['In Progress'], $this->admin);

        $rows = DB::table('project_step_movements')->where('project_id', $this->project->id)->orderBy('seq')->get();

        expect($rows)->toHaveCount(2)
            ->and($rows[0]->exited_at)->not->toBeNull()
            ->and($rows[0]->duration_seconds)->not->toBeNull()   // generated by MySQL
            ->and($rows[1]->exited_at)->toBeNull()
            ->and($rows[1]->from_step_id)->toBe($rows[0]->to_step_id);
    });

    it('sets first_active_at once and never moves it', function () {
        $recorder = app(MovementRecorder::class);

        $recorder->recordMove($this->project, $this->steps['In Progress'], $this->admin);
        $firstActive = $this->project->fresh()->first_active_at;

        // Out to a waiting step and back into work again.
        $recorder->recordMove($this->project->fresh(), $this->steps['New'], $this->admin);
        $recorder->recordMove($this->project->fresh(), $this->steps['In Progress'], $this->admin);

        expect($this->project->fresh()->first_active_at->timestamp)->toBe($firstActive->timestamp);
    });

    it('is a no-op when dropped back on the same step', function () {
        // A card picked up and put down must not write a movement row — that would
        // reset its step clock and corrupt the one metric the board exists to show.
        $recorder = app(MovementRecorder::class);
        $recorder->recordMove($this->project, $this->steps['In Progress'], $this->admin);

        $before = DB::table('project_step_movements')->where('project_id', $this->project->id)->count();
        $recorder->recordMove($this->project->fresh(), $this->steps['In Progress'], $this->admin);

        expect(DB::table('project_step_movements')->where('project_id', $this->project->id)->count())->toBe($before);
    });

    it('computes cycle time from first work to completion', function () {
        $recorder = app(MovementRecorder::class);
        $recorder->recordMove($this->project, $this->steps['In Progress'], $this->admin);
        $recorder->recordMove($this->project->fresh(), $this->steps['Done'], $this->admin);

        $fresh = $this->project->fresh();

        expect($fresh->first_terminal_at)->not->toBeNull()
            ->and($fresh->cycle_time_seconds)->not->toBeNull()
            ->and($fresh->lead_time_seconds)->not->toBeNull()
            ->and($fresh->skipped_active)->toBeFalse();
    });

    it('leaves cycle time NULL when a project skips work entirely', function () {
        // M-D7 — coercing this to zero would silently drag every median down.
        app(MovementRecorder::class)->recordMove($this->project, $this->steps['Done'], $this->admin);

        $fresh = $this->project->fresh();

        expect($fresh->cycle_time_seconds)->toBeNull()
            ->and($fresh->skipped_active)->toBeTrue()
            ->and($fresh->lead_time_seconds)->not->toBeNull();
    });

    // ═══════════════════════════════════════════════════════════════════════════
    // REGRESSION TEST — VERIFICATION.md metrics-2.
    //
    // Original behaviour: once first_terminal_at was set, the cycle-time branch never
    // ran again. A card mis-dragged straight to Done, then correctly reopened and
    // genuinely worked, could NEVER acquire a cycle time — permanently excluded from
    // every median, permanently counted as "workflow bypassed", and permanently in
    // violation of the design's own invariant, so the nightly verifier would flag it
    // as unfixable drift and train the team to ignore the alert.
    // ═══════════════════════════════════════════════════════════════════════════
    it('heals cycle time when a mis-dragged project is reopened and actually worked', function () {
        $recorder = app(MovementRecorder::class);

        // The mistake: Backlog straight to Done.
        $recorder->recordMove($this->project, $this->steps['Done'], $this->admin);
        expect($this->project->fresh()->skipped_active)->toBeTrue();

        // The correction, next day: reopened and genuinely worked, then finished.
        $recorder->recordMove($this->project->fresh(), $this->steps['In Progress'], $this->admin);
        $recorder->recordMove($this->project->fresh(), $this->steps['Done'], $this->admin);

        $fresh = $this->project->fresh();

        expect($fresh->cycle_time_seconds)->not->toBeNull()
            ->and($fresh->skipped_active)->toBeFalse()
            ->and($fresh->reopen_count)->toBe(1);
    });

    it('freezes first_terminal_at across a reopen so throughput cannot be rewritten', function () {
        $recorder = app(MovementRecorder::class);
        $recorder->recordMove($this->project, $this->steps['In Progress'], $this->admin);
        $recorder->recordMove($this->project->fresh(), $this->steps['Done'], $this->admin);

        $completedAt = $this->project->fresh()->first_terminal_at;

        $recorder->recordMove($this->project->fresh(), $this->steps['In Progress'], $this->admin);
        $recorder->recordMove($this->project->fresh(), $this->steps['Done'], $this->admin);

        expect($this->project->fresh()->first_terminal_at->timestamp)->toBe($completedAt->timestamp);
    });
});

describe('the activity clock', function () {

    beforeEach(function () {
        $this->project = app(ProjectService::class)->create($this->tracker, ['name' => 'CCTV storage'], $this->admin);
    });

    it('clears an AUTO-raised stall when something happens', function () {
        $this->project->forceFill([
            'health' => ProjectHealth::Stalled,
            'health_source' => HealthSource::Auto,
            'stall_notified_at' => now(),
        ])->save();

        app(ActivityRecorder::class)->record($this->project->fresh(), 'comment', $this->admin);

        $fresh = $this->project->fresh();

        expect($fresh->health)->toBe(ProjectHealth::OnTrack)
            // Cleared so the NEXT stall episode can notify again.
            ->and($fresh->stall_notified_at)->toBeNull();
    });

    it('does NOT overrule a human who marked it stalled deliberately', function () {
        $this->project->forceFill([
            'health' => ProjectHealth::Stalled,
            'health_source' => HealthSource::Manual,
            'health_reason' => 'Waiting on vendor RMA',
        ])->save();

        app(ActivityRecorder::class)->record($this->project->fresh(), 'comment', $this->admin);

        expect($this->project->fresh()->health)->toBe(ProjectHealth::Stalled);
    });

    it('can record a feed entry that does not reset the stall clock', function () {
        // The stall job's own writes must not un-stall everything it just flagged.
        $before = $this->project->last_activity_at;

        $this->travel(2)->minutes();
        app(ActivityRecorder::class)->record($this->project->fresh(), 'stall_detected', null, [], countsAsActivity: false);

        expect($this->project->fresh()->last_activity_at->timestamp)->toBe($before->timestamp)
            ->and(DB::table('project_activities')->where('type', 'stall_detected')->exists())->toBeTrue();
    });
});

describe('notifications are queued inside the move transaction', function () {

    it('writes outbox rows atomically with the movement', function () {
        // data-model-3: written after commit, a crash in that window left the move
        // recorded with no notification row anywhere — invisible by construction.
        $member = makeUser('joy@gmail.com');
        app(TrackerService::class)->addMember($this->tracker, $member, $this->admin);

        $project = app(ProjectService::class)->create($this->tracker, ['name' => 'Payroll'], $this->admin);
        DB::table('notification_outbox')->delete();

        app(MovementRecorder::class)->recordMove($project, $this->steps['In Progress'], $member);

        $rows = DB::table('notification_outbox')->get();

        expect($rows)->not->toBeEmpty()
            // The actor gets no email about their own action.
            ->and($rows->pluck('user_id')->all())->not->toContain($member->id)
            ->and($rows->first()->status)->toBe('pending');
    });

    it('coalesces repeated moves of the same card into one pending row', function () {
        $project = app(ProjectService::class)->create($this->tracker, ['name' => 'Wi-Fi survey'], $this->admin);
        $mover = makeUser('paolo@gmail.com');
        app(TrackerService::class)->addMember($this->tracker, $mover, $this->admin);

        DB::table('notification_outbox')->delete();

        $recorder = app(MovementRecorder::class);
        $recorder->recordMove($project, $this->steps['New'], $mover);
        $recorder->recordMove($project->fresh(), $this->steps['In Progress'], $mover);
        $recorder->recordMove($project->fresh(), $this->steps['Done'], $mover);

        // FR-7.8 — one email describing the net movement, not three describing each
        // twitch of someone tidying the board.
        $pending = DB::table('notification_outbox')
            ->where('event_type', 'project.moved')->where('status', 'pending')->get();

        expect($pending)->toHaveCount(1);

        $payload = json_decode($pending->first()->payload, true);

        expect($payload['coalesced'])->toBe(3)
            ->and($payload['to_step'])->toBe('Done');   // latest destination
    });
});
