<?php

namespace App\Services\Projects;

use App\Enums\StepType;
use App\Models\Project;
use App\Models\ProjectStepMovement;
use App\Models\Step;
use App\Models\User;
use App\Services\Notifications\OutboxWriter;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * THE ONLY WRITE PATH into project_step_movements.
 *
 * Every metric in the system is derived from that table, and the denormalized
 * read-model columns on `projects` are materialisations of it. Any code path that
 * changes a project's step WITHOUT going through here silently corrupts every metric
 * downstream, with no error and no symptom until someone questions a number months
 * later. Hence one seam, and `worktrack:rebuild-caches --check` as the drift detector.
 */
class MovementRecorder
{
    public function __construct(
        private ActivityRecorder $activity,
        private OutboxWriter $outbox,
    ) {}

    /**
     * Open movement #1 when a project is created (M-D22).
     *
     * No project ever exists without an open movement — otherwise "days in current
     * step" has no origin and the project is invisible to aging reports.
     */
    /**
     * @param  array<string, mixed>  $details  merged into the 'created' activity row so
     *                                         the log can show what the form actually
     *                                         collected — owner, assignees, tags, dates —
     *                                         without a second row per field on a project
     *                                         that did not exist a moment ago.
     */
    public function recordCreation(Project $project, Step $step, ?User $actor = null, array $details = []): ProjectStepMovement
    {
        return DB::transaction(function () use ($project, $step, $actor, $details) {
            $movement = ProjectStepMovement::create([
                'tracker_id' => $project->tracker_id,
                'project_id' => $project->id,
                'seq' => 1,
                'from_step_id' => null,
                'from_step_type' => null,
                'to_step_id' => $step->id,
                'to_step_type' => $step->type,

                // Snapshot, not a live join — department is editable per project, so
                // without this a rebuild would stamp today's department onto all of
                // history (VERIFICATION.md metrics-1).
                'department_id' => $project->department_id,

                'moved_by_user_id' => $actor?->id,
                'reason' => 'created',
                'entered_at' => $project->created_at ?? now(),
            ]);

            $project->forceFill([
                'current_step_type' => $step->type,
                'current_step_entered_at' => $movement->entered_at,
                'first_active_at' => $step->type === StepType::Active ? $movement->entered_at : null,
            ])->save();

            // Seeds last_activity_at. Critical: if it were left NULL, the stall
            // predicate TIMESTAMPDIFF(..., NULL, NOW()) >= threshold evaluates to NULL
            // and the row is NEVER selected — so a project created and never touched
            // would be permanently invisible to stall detection, which is an exact
            // inversion of this product's primary purpose (VERIFICATION.md metrics-4).
            $this->activity->record($project, 'created', $actor, [
                'step' => $step->name,
                ...array_filter($details, fn ($v) => $v !== null && $v !== []),
            ]);

            return $movement;
        });
    }

    /**
     * Move a project to another step: close the open interval, open the next.
     *
     * @param  string  $reason  'user_move' | 'system' | 'correction'
     */
    public function recordMove(Project $project, Step $toStep, ?User $actor = null, string $reason = 'user_move'): ProjectStepMovement
    {
        return DB::transaction(function () use ($project, $toStep, $actor, $reason) {
            // Serialise concurrent moves of the same card. Without this, two
            // simultaneous drops can both read seq=3 and race on the unique
            // (project_id, seq) index — one drop silently fails.
            $locked = Project::whereKey($project->id)->lockForUpdate()->firstOrFail();

            $open = ProjectStepMovement::where('project_id', $locked->id)
                ->whereNull('exited_at')
                ->lockForUpdate()
                ->first();

            if ($open !== null && $open->to_step_id === $toStep->id) {
                return $open;   // dropped back where it started; nothing happened
            }

            $now = now();

            if ($open !== null) {
                // The ONLY field ever written to an existing movement row, and only
                // once. duration_seconds is generated by MySQL from the timestamps, so
                // it cannot drift from them.
                $open->forceFill(['exited_at' => $now])->save();

                // ...but a STORED generated column is computed by the ENGINE, so the
                // value MySQL just derived is not in the in-memory model: $open still
                // holds the NULL duration_seconds it carried while the interval was open.
                // Both readers below want the closed duration — FR-7.2 requires "how long
                // it sat in the previous step" in the notification email, and the activity
                // row records the same figure — so without this re-read both were silently
                // null on every move the system recorded.
                $open->refresh();
            }

            $next = ProjectStepMovement::create([
                'tracker_id' => $locked->tracker_id,
                'project_id' => $locked->id,
                'seq' => ($open?->seq ?? 0) + 1,
                'from_step_id' => $open?->to_step_id,
                'from_step_type' => $open?->to_step_type,
                'to_step_id' => $toStep->id,
                'to_step_type' => $toStep->type,
                'department_id' => $locked->department_id,
                'moved_by_user_id' => $actor?->id,
                'reason' => $reason,
                'entered_at' => $now,
            ]);

            $this->applyMetrics($locked, $next, $now);

            $this->activity->record($locked, 'step_move', $actor, [
                'from' => $open?->to_step_id,
                'to' => $toStep->id,
                'to_step_name' => $toStep->name,
                'seconds_in_previous_step' => $open?->duration_seconds,
            ]);

            // ═══════════════════════════════════════════════════════════════════════
            // CRITICAL — VERIFICATION.md data-model-3.
            // The outbox rows are written INSIDE this transaction. The original design
            // put them after commit, which is a dual-write, not an outbox: a crash in
            // that window left the move durably recorded and visible on the board with
            // no notification row anywhere — not in outbox, not in failed_jobs, not in
            // the FR-10.5 pending count. The failure was invisible by construction,
            // because its symptom is the ABSENCE of a row rather than a failed one.
            // Only the queue DISPATCH belongs after commit.
            // ═══════════════════════════════════════════════════════════════════════
            $this->outbox->queueStepChange($locked, $open, $next, $actor);

            return $next;
        });
    }

    /**
     * Whole elapsed seconds, FLOORED.
     *
     * diffInSeconds() returns a float, and writing a float to an INT column lets MySQL
     * round it — so a 0.4-second cycle was being stored as 1 second, and a genuinely
     * instantaneous one as 1 rather than 0. Durations must be deterministic and must
     * never round upward: the difference between 0 and 1 second is meaningless, but the
     * difference between "stored what happened" and "stored something near it" is not,
     * in the one table every metric is derived from.
     */
    private function elapsedSeconds(\DateTimeInterface|string $from, \DateTimeInterface $to): int
    {
        return (int) floor(Carbon::parse($from)->diffInSeconds($to, absolute: true));
    }

    /**
     * Maintain the derived read model. Everything here is recomputable from history;
     * this is a cache for NFR-P1, not a second source of truth.
     */
    private function applyMetrics(Project $project, ProjectStepMovement $movement, \DateTimeInterface $now): void
    {
        $updates = [
            'current_step_type' => $movement->to_step_type,
            'current_step_entered_at' => $now,
            'step_id' => $movement->to_step_id,
        ];

        $enteringActive = $movement->to_step_type === StepType::Active;
        $enteringTerminal = $movement->to_step_type === StepType::Terminal;
        $leavingTerminal = $movement->from_step_type === StepType::Terminal;

        // Write-once anchor: the first time real work began. Never moves, so bouncing
        // between active steps cannot restart the cycle clock.
        if ($enteringActive && $project->first_active_at === null) {
            $updates['first_active_at'] = $now;
        }

        if ($leavingTerminal) {
            // M-D4 — a project dragged backward out of Done rejoins aging and the
            // watchlist, but first_terminal_at and the recorded cycle time stay frozen
            // so throughput history cannot be rewritten by a correction.
            $updates['reopen_count'] = $project->reopen_count + 1;
        }

        if ($enteringTerminal) {
            $firstActive = $updates['first_active_at'] ?? $project->first_active_at;

            if ($project->first_terminal_at === null) {
                $updates['first_terminal_at'] = $now;
                $updates['lead_time_seconds'] = $this->elapsedSeconds($project->created_at, $now);

                if ($firstActive !== null) {
                    $updates['cycle_time_seconds'] = $this->elapsedSeconds($firstActive, $now);
                    $updates['skipped_active'] = false;
                } else {
                    // Dragged intake -> terminal, never worked. cycle_time stays NULL and
                    // is excluded from averages — coercing it to zero would silently drag
                    // every median down (M-D7).
                    $updates['skipped_active'] = true;
                }
            } elseif ($project->cycle_time_seconds === null && $firstActive !== null) {
                // ═══════════════════════════════════════════════════════════════════
                // CRITICAL FIX — VERIFICATION.md metrics-2 (self-healing).
                // Original behaviour: once first_terminal_at was set, the cycle-time
                // branch never ran again. So a card mis-dragged straight to Done, then
                // correctly reopened and genuinely worked for 30 days, could NEVER
                // acquire a cycle time. It stayed excluded from every median forever,
                // stayed counted in the "workflow being bypassed" data-quality figure
                // forever, and permanently violated the design's own invariant — so the
                // nightly verifier would report it as drift with no possible remediation,
                // training the team to ignore the alert.
                // Now: acquiring a real active anchor heals both fields.
                // ═══════════════════════════════════════════════════════════════════
                $updates['cycle_time_seconds'] = $this->elapsedSeconds($firstActive, $now);
                $updates['skipped_active'] = false;
            }
        }

        $project->forceFill($updates)->save();
    }
}
